services:
  db:
    build: db
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
      - db_log:/var/log/postgresql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - METASFRESH_USERNAME=metasfresh
      - METASFRESH_PASSWORD=metasfresh
      - METASFRESH_DBNAME=metasfresh
      - DB_SYSPASS=System
      - POSTGRES_PASSWORD=ip2LmNzXX8p8iXg9lZTWEJ9524kQDbXFudB7LR03T-xK9fLweX3TLMkA2AYcEiaS

  app:
    build: app
    hostname: app
    depends_on:
      - db:db
      - rabbitmq
      - search
    # ports:
    #   - "8282:8282"
    #   - "8788:8788"
    restart: unless-stopped
    volumes:
      - app_heapdump:/opt/metasfresh/heapdump
      - app_lib:/opt/metasfresh/external-lib
      - app_log:/opt/metasfresh/log
      - /etc/localtime:/etc/localtime:ro
    environment:
      - METASFRESH_HOME=/opt/metasfresh

  webapi:
    build: webapi
    depends_on:
      - app
      - db
      - rabbitmq
      - search
    # ports:
    #   - "8789:8789"
    #   - "8080:8080"
    restart: unless-stopped
    volumes:
      - webapi_heapdump:/opt/metasfresh-webui-api/heapdump
      - webapi_log:/opt/metasfresh-webui-api/log
      - /etc/localtime:/etc/localtime:ro

  webui:
    build: webui
    depends_on:
      - webapi
    ports:
      - "53525:80"
      - "53526:443"
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - WEBAPI_URL=http://home.friedrich.ventures:53525

  rabbitmq:
    build: rabbitmq
    # ports:
    #   - "5672:5672"
    restart: unless-stopped
    volumes:
      - rabbitmq:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq/log
      - /etc/localtime:/etc/localtime:ro
    environment:
      RABBITMQ_DEFAULT_USER: "metasfresh"
      RABBITMQ_DEFAULT_PASS: "metasfresh"
      RABBITMQ_DEFAULT_VHOST: "/"

  search:
    build: search
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    # ports:
    #   - "9200:9200"
    #   - "9300:9300"
    volumes:
      - search:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "ES_JAVA_OPTS=-Xms128M -Xmx256m"
    restart: unless-stopped

volumes:
  app_heapdump:
  app_lib:
  app_log:
  db:
  db_log:
  rabbitmq:
  rabbitmq_log:
  search:
  webapi_heapdump:
  webapi_log:
